---
- name: Rulebook login vcenter 
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: login vcenter 
      condition: event.payload.backlog[0].fields.vmw_login_action == "Successful"
      action:
        run_job_template:
          name: login-vcenter # Ten cua template tren AWX server
          organization: Default
          job_args:
            extra_vars:
              vmw_mess: "{{ event.payload.backlog[0].message  }}"
              # vmw_action: "{{ event.payload.backlog[0].message }}"
